import MasterPage from "../components/Master"

const Nosotros = () => (
  <MasterPage>
    <div>
      <h1 className="text-center">Sobre nosotros</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae quod cupiditate possimus animi! Velit quam voluptates et commodi enim eligendi laudantium blanditiis modi ipsam unde repudiandae pariatur ut, possimus ipsum corrupti cumque molestiae officiis corporis quae labore eos at quidem explicabo? Praesentium, tenetur minima sint vitae aperiam maxime enim, cupiditate impedit asperiores repellendus mollitia nostrum reiciendis tempore nisi voluptatem quidem dicta quos, laborum odio? Provident dolore at voluptatibus vitae doloribus excepturi adipisci odit, totam ullam asperiores ea culpa voluptatum repudiandae. Expedita nobis maxime quibusdam vitae. Iste inventore eius earum quasi quisquam rem quam porro alias! Voluptate aliquid maiores numquam reiciendis, iste eligendi rerum temporibus delectus ipsum error debitis ipsam nobis molestias nostrum voluptatem mollitia. Obcaecati saepe in iure atque, delectus quo asperiores laborum! Obcaecati eaque vel neque inventore beatae. Earum delectus dignissimos impedit ut necessitatibus eius unde illo corrupti odio id esse commodi ab voluptatibus autem repellendus, voluptate veniam. Possimus doloribus voluptas illum recusandae. Et, alias nulla tempore dolores dicta quisquam reprehenderit praesentium! Quae quibusdam aut odit illum reprehenderit necessitatibus vero aliquid exercitationem doloribus facilis commodi illo molestias quas consequuntur consectetur in accusamus veniam assumenda ipsum eligendi, ex at! Voluptatem fugiat eaque temporibus, vero voluptatum iste quod officiis unde consectetur?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum id omnis consectetur dicta, quae vitae reprehenderit minus atque tempora tenetur eum ratione quas iste corrupti. Repellendus illo, soluta optio incidunt minus odit ad autem fugiat, placeat tenetur deserunt repellat maxime! Ut ducimus magnam doloribus ad suscipit error sed commodi ipsum quia, aliquam expedita quo accusantium ex perspiciatis voluptate? Voluptatum sapiente molestias iusto nesciunt impedit error a, amet, doloribus ducimus, nihil numquam. Rem officiis perspiciatis animi repudiandae accusamus et asperiores perferendis, excepturi quis quo quasi voluptatem tempora rerum dolores quibusdam impedit laborum dolore consequatur voluptatum recusandae quia aut quas hic qui.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis aut, aspernatur nostrum mollitia optio illo tempore blanditiis et ipsum repellat sint earum. Voluptatibus maxime obcaecati vero enim recusandae laboriosam libero officia nihil, at ab distinctio cupiditate provident. Id distinctio ratione officiis eveniet doloribus molestiae reiciendis ad, laboriosam vel, animi beatae sed ducimus tempore accusamus harum error itaque earum enim? Maiores, illo ea odio aperiam aliquid officia aut harum obcaecati natus quisquam iure recusandae, dolorem ab.</p>
    </div>
  </MasterPage>
)

export default Nosotros